import './globals.css'
import { Inter } from 'next/font/google'
import  Header  from "@/components/layouts/header"
import  Footer  from "@/components/layouts/footer"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clothing Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Header/>
        <main className='px-8'>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
